### ISSUE TITLE
Mapstruct Support

### ISSUE THREAD

**Issue by myatmin** [GabrielBB/vscode-lombok#29]
Hi,
Thank you  so much for this useful extension.
Can you please help add in the AstModifyingAnnotationProcessor and other required classes to the JAR for the Mapstruct support?
The [source issue](https://github.com/mapstruct/mapstruct/issues/1159) on Mapstruct which proposed the fix for adding required classes to the lombok JAR.
Meanwhile as lombok is not actively supporting to this issue, I guess the best working fix for the time being will be at the extension level for the VSCode users. Thank you!

**Comment by jc040993** [comment]
Hi,

Any update on this? Am struggling with this issue as vs-code is running java builds continuously.

Found below from Java server logs
```
Failed to read AstModifyingAnnotationProcessor. Reading next processor.
Reason: java.lang.NoClassDefFoundError: org/mapstruct/ap/spi/AstModifyingAnnotationProcessor
  	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
  	at java.base/java.lang.ClassLoader.defineClass(Unknown Source)
  	at java.base/java.security.SecureClassLoader.defineClass(Unknown Source)
  	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(Unknown Source)
  	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(Unknown Source)
  	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(Unknown Source)
  	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source)
  	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(Unknown Source)
...
```
Please let me know if any logs required. Any help would be appreciated. Thanks.
